$schema: "http://json-schema.org/draft-06/schema#"

description: seq2science single-cell atac-seq configuration

properties:
  snaptools_opt:
    description: "snaptools optional arguments for snaptools snap-pre, from snaptools (https://github.com/r3fang/SnapTools). For more info run snaptools snap-pre -h"
    default: --min-flen=0 --max-flen=1000 --keep-single=FALSE --keep-secondary=FALSE --overwrite=True --min-cov=100 --verbose=True
  bin_opt:
    description: snaptools optional arguments for snaptools snap-add-bmat, from snaptools (https://github.com/r3fang/SnapTools). For more info run snaptools snap-add-bmat -h 
      --bin-size-list BIN_SIZE_LIST [BIN_SIZE_LIST ...]
                        a list of bin size(s) to create the cell-by-bin count matrix. The genome will be divided into bins of the equal size of --bin-size-list to create the cell x bin count matrix. If more than one bin size are given, snaptools will generate a list of cell x bin
                        matrices of different resolutions and stored in the same snap file. (default: [5000])
      --tmp-folder TMP_FOLDER
                            a directory to store temporary files. If not given, snaptools will automatically generate a temporary location to store temporary files. (default: None)
      --verbose VERBOSE     a boolen tag indicates output the progress. (default: True)
    default: --bin-size-list 5000 --verbose=True
